#!/usr/bin/env bash
set -euo pipefail

# UERANSIM software-only build for the lab. No RF is generated by UERANSIM.
# Pinned to a known tagged release; review upstream release notes before upgrading.
UERANSIM_VERSION="v3.3.0"
WORKDIR="${WORKDIR:-$HOME/src}"

sudo apt update
sudo apt install -y git cmake g++ make libsctp-dev lksctp-tools libssl-dev
mkdir -p "$WORKDIR"
cd "$WORKDIR"

if [[ ! -d UERANSIM/.git ]]; then
  git clone https://github.com/aligungr/UERANSIM.git
fi
cd UERANSIM
git fetch --tags --force
git checkout "$UERANSIM_VERSION"

rm -rf build
make -j"$(nproc)"

echo "UERANSIM built from ${UERANSIM_VERSION}. Binaries are under build/."
